# This is a basic workflow to help you get started with Actions

name: Jest Tests

# Controls when the workflow will run
on:
  push:
    branches: [features/**]
  # Triggers the workflow on push events to "feature" and 
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        
    Jest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: npm test

        #- name: Run Tests
          #run: |
            #npm install 
            #npm test
            